spring.application.name=LearnNShare

spring.datasource.url=jdbc:mysql://reseau.proxy.rlwy.net:17497/railway
spring.datasource.username=root
spring.datasource.password=vywWnMhhrVQLIhMsHIkEvQuBbkEwKekb

cloudinary.cloud-name=dq5fsjo2f
cloudinary.api-key=674529373535319
cloudinary.api-secret=TiFJ6hG88pKxuUB9-7d7Z5ISIhc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

file.upload-dir=uploads/

server.port=${PORT:8080}